version: "3.8"

services:

  web:
    build: .
    command: sh ./docker-entrypoint.sh
    volumes:
      - data:/app/data/
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  redis:
    image: redis:7.0.6-alpine
    volumes:
      - redis-data:/data/
    restart: always

volumes:
  postgres_data:
  redis-data:
  prometheus-data:
